// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: chainmaker_server.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ChainMakerVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChainMakerVersionRequest) Reset() {
	*x = ChainMakerVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainmaker_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainMakerVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMakerVersionRequest) ProtoMessage() {}

func (x *ChainMakerVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainmaker_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMakerVersionRequest.ProtoReflect.Descriptor instead.
func (*ChainMakerVersionRequest) Descriptor() ([]byte, []int) {
	return file_chainmaker_server_proto_rawDescGZIP(), []int{0}
}

type ChainMakerVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ChainMakerVersionResponse) Reset() {
	*x = ChainMakerVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainmaker_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainMakerVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMakerVersionResponse) ProtoMessage() {}

func (x *ChainMakerVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainmaker_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMakerVersionResponse.ProtoReflect.Descriptor instead.
func (*ChainMakerVersionResponse) Descriptor() ([]byte, []int) {
	return file_chainmaker_server_proto_rawDescGZIP(), []int{1}
}

func (x *ChainMakerVersionResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChainMakerVersionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChainMakerVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_chainmaker_server_proto protoreflect.FileDescriptor

var file_chainmaker_server_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x1a, 0x0a,
	0x18, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x63, 0x0a, 0x19, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x21,
	0x5a, 0x1f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x6f, 0x72, 0x67,
	0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chainmaker_server_proto_rawDescOnce sync.Once
	file_chainmaker_server_proto_rawDescData = file_chainmaker_server_proto_rawDesc
)

func file_chainmaker_server_proto_rawDescGZIP() []byte {
	file_chainmaker_server_proto_rawDescOnce.Do(func() {
		file_chainmaker_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_chainmaker_server_proto_rawDescData)
	})
	return file_chainmaker_server_proto_rawDescData
}

var file_chainmaker_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chainmaker_server_proto_goTypes = []interface{}{
	(*ChainMakerVersionRequest)(nil),  // 0: pb.ChainMakerVersionRequest
	(*ChainMakerVersionResponse)(nil), // 1: pb.ChainMakerVersionResponse
}
var file_chainmaker_server_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chainmaker_server_proto_init() }
func file_chainmaker_server_proto_init() {
	if File_chainmaker_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chainmaker_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainMakerVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainmaker_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainMakerVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chainmaker_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chainmaker_server_proto_goTypes,
		DependencyIndexes: file_chainmaker_server_proto_depIdxs,
		MessageInfos:      file_chainmaker_server_proto_msgTypes,
	}.Build()
	File_chainmaker_server_proto = out.File
	file_chainmaker_server_proto_rawDesc = nil
	file_chainmaker_server_proto_goTypes = nil
	file_chainmaker_server_proto_depIdxs = nil
}
