// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: consensus.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ConsensusType int32

const (
	ConsensusType_SOLO     ConsensusType = 0
	ConsensusType_TBFT     ConsensusType = 1
	ConsensusType_MBFT     ConsensusType = 2
	ConsensusType_HOTSTUFF ConsensusType = 3
	ConsensusType_RAFT     ConsensusType = 4
	ConsensusType_POW      ConsensusType = 10
)

// Enum value maps for ConsensusType.
var (
	ConsensusType_name = map[int32]string{
		0:  "SOLO",
		1:  "TBFT",
		2:  "MBFT",
		3:  "HOTSTUFF",
		4:  "RAFT",
		10: "POW",
	}
	ConsensusType_value = map[string]int32{
		"SOLO":     0,
		"TBFT":     1,
		"MBFT":     2,
		"HOTSTUFF": 3,
		"RAFT":     4,
		"POW":      10,
	}
)

func (x ConsensusType) Enum() *ConsensusType {
	p := new(ConsensusType)
	*p = x
	return p
}

func (x ConsensusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsensusType) Descriptor() protoreflect.EnumDescriptor {
	return file_consensus_proto_enumTypes[0].Descriptor()
}

func (ConsensusType) Type() protoreflect.EnumType {
	return &file_consensus_proto_enumTypes[0]
}

func (x ConsensusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsensusType.Descriptor instead.
func (ConsensusType) EnumDescriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{0}
}

type VerifyResult_Code int32

const (
	VerifyResult_SUCCESS VerifyResult_Code = 0
	VerifyResult_FAIL    VerifyResult_Code = 1
)

// Enum value maps for VerifyResult_Code.
var (
	VerifyResult_Code_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
	}
	VerifyResult_Code_value = map[string]int32{
		"SUCCESS": 0,
		"FAIL":    1,
	}
)

func (x VerifyResult_Code) Enum() *VerifyResult_Code {
	p := new(VerifyResult_Code)
	*p = x
	return p
}

func (x VerifyResult_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifyResult_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_consensus_proto_enumTypes[1].Descriptor()
}

func (VerifyResult_Code) Type() protoreflect.EnumType {
	return &file_consensus_proto_enumTypes[1]
}

func (x VerifyResult_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerifyResult_Code.Descriptor instead.
func (VerifyResult_Code) EnumDescriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{0, 0}
}

type VerifyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerifiedBlock *Block            `protobuf:"bytes,1,opt,name=verified_block,json=verifiedBlock,proto3" json:"verified_block,omitempty"`
	Code          VerifyResult_Code `protobuf:"varint,2,opt,name=code,proto3,enum=pb.VerifyResult_Code" json:"code,omitempty"`
	Msg           string            `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *VerifyResult) Reset() {
	*x = VerifyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResult) ProtoMessage() {}

func (x *VerifyResult) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResult.ProtoReflect.Descriptor instead.
func (*VerifyResult) Descriptor() ([]byte, []int) {
	return file_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyResult) GetVerifiedBlock() *Block {
	if x != nil {
		return x.VerifiedBlock
	}
	return nil
}

func (x *VerifyResult) GetCode() VerifyResult_Code {
	if x != nil {
		return x.Code
	}
	return VerifyResult_SUCCESS
}

func (x *VerifyResult) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_consensus_proto protoreflect.FileDescriptor

var file_consensus_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x30, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0d, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x29, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x1d, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10,
	0x01, 0x2a, 0x4e, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4f, 0x4c, 0x4f, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x54, 0x42, 0x46, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x42, 0x46, 0x54, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x48, 0x4f, 0x54, 0x53, 0x54, 0x55, 0x46, 0x46, 0x10, 0x03, 0x12, 0x08,
	0x0a, 0x04, 0x52, 0x41, 0x46, 0x54, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x4f, 0x57, 0x10,
	0x0a, 0x42, 0x21, 0x5a, 0x1f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e,
	0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2d, 0x67,
	0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consensus_proto_rawDescOnce sync.Once
	file_consensus_proto_rawDescData = file_consensus_proto_rawDesc
)

func file_consensus_proto_rawDescGZIP() []byte {
	file_consensus_proto_rawDescOnce.Do(func() {
		file_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(file_consensus_proto_rawDescData)
	})
	return file_consensus_proto_rawDescData
}

var file_consensus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_consensus_proto_goTypes = []interface{}{
	(ConsensusType)(0),     // 0: pb.ConsensusType
	(VerifyResult_Code)(0), // 1: pb.VerifyResult.Code
	(*VerifyResult)(nil),   // 2: pb.VerifyResult
	(*Block)(nil),          // 3: pb.Block
}
var file_consensus_proto_depIdxs = []int32{
	3, // 0: pb.VerifyResult.verified_block:type_name -> pb.Block
	1, // 1: pb.VerifyResult.code:type_name -> pb.VerifyResult.Code
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_consensus_proto_init() }
func file_consensus_proto_init() {
	if File_consensus_proto != nil {
		return
	}
	file_block_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_consensus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consensus_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_proto_goTypes,
		DependencyIndexes: file_consensus_proto_depIdxs,
		EnumInfos:         file_consensus_proto_enumTypes,
		MessageInfos:      file_consensus_proto_msgTypes,
	}.Build()
	File_consensus_proto = out.File
	file_consensus_proto_rawDesc = nil
	file_consensus_proto_goTypes = nil
	file_consensus_proto_depIdxs = nil
}
