// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: idmgmt_group.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Serialized member of blockchain
type GroupConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthType                 string   `protobuf:"bytes,2,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	OrgInfo                  []byte   `protobuf:"bytes,3,opt,name=org_info,json=orgInfo,proto3" json:"org_info,omitempty"`
	TrustedRootCerts         [][]byte `protobuf:"bytes,4,rep,name=trusted_root_certs,json=trustedRootCerts,proto3" json:"trusted_root_certs,omitempty"`
	TrustedIntermediateCerts [][]byte `protobuf:"bytes,5,rep,name=trusted_intermediate_certs,json=trustedIntermediateCerts,proto3" json:"trusted_intermediate_certs,omitempty"`
}

func (x *GroupConfig) Reset() {
	*x = GroupConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmgmt_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupConfig) ProtoMessage() {}

func (x *GroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_idmgmt_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupConfig.ProtoReflect.Descriptor instead.
func (*GroupConfig) Descriptor() ([]byte, []int) {
	return file_idmgmt_group_proto_rawDescGZIP(), []int{0}
}

func (x *GroupConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupConfig) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *GroupConfig) GetOrgInfo() []byte {
	if x != nil {
		return x.OrgInfo
	}
	return nil
}

func (x *GroupConfig) GetTrustedRootCerts() [][]byte {
	if x != nil {
		return x.TrustedRootCerts
	}
	return nil
}

func (x *GroupConfig) GetTrustedIntermediateCerts() [][]byte {
	if x != nil {
		return x.TrustedIntermediateCerts
	}
	return nil
}

var File_idmgmt_group_proto protoreflect.FileDescriptor

var file_idmgmt_group_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x64, 0x6d, 0x67, 0x6d, 0x74, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xc1, 0x01, 0x0a, 0x0b, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2c, 0x0a, 0x12, 0x74, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x6f, 0x74,
	0x5f, 0x63, 0x65, 0x72, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x10, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x65, 0x72, 0x74, 0x73, 0x12, 0x3c,
	0x0a, 0x1a, 0x74, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x18, 0x74, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x43, 0x65, 0x72, 0x74, 0x73, 0x42, 0x21, 0x5a, 0x1f,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idmgmt_group_proto_rawDescOnce sync.Once
	file_idmgmt_group_proto_rawDescData = file_idmgmt_group_proto_rawDesc
)

func file_idmgmt_group_proto_rawDescGZIP() []byte {
	file_idmgmt_group_proto_rawDescOnce.Do(func() {
		file_idmgmt_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_idmgmt_group_proto_rawDescData)
	})
	return file_idmgmt_group_proto_rawDescData
}

var file_idmgmt_group_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_idmgmt_group_proto_goTypes = []interface{}{
	(*GroupConfig)(nil), // 0: pb.GroupConfig
}
var file_idmgmt_group_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idmgmt_group_proto_init() }
func file_idmgmt_group_proto_init() {
	if File_idmgmt_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idmgmt_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idmgmt_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idmgmt_group_proto_goTypes,
		DependencyIndexes: file_idmgmt_group_proto_depIdxs,
		MessageInfos:      file_idmgmt_group_proto_msgTypes,
	}.Build()
	File_idmgmt_group_proto = out.File
	file_idmgmt_group_proto_rawDesc = nil
	file_idmgmt_group_proto_goTypes = nil
	file_idmgmt_group_proto_depIdxs = nil
}
