// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: mult_sign.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 多签管理
type VoteStatus int32

const (
	// 不同意
	VoteStatus_DISAGREE VoteStatus = 0
	// 同意
	VoteStatus_AGREE VoteStatus = 1
)

// Enum value maps for VoteStatus.
var (
	VoteStatus_name = map[int32]string{
		0: "DISAGREE",
		1: "AGREE",
	}
	VoteStatus_value = map[string]int32{
		"DISAGREE": 0,
		"AGREE":    1,
	}
)

func (x VoteStatus) Enum() *VoteStatus {
	p := new(VoteStatus)
	*p = x
	return p
}

func (x VoteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mult_sign_proto_enumTypes[0].Descriptor()
}

func (VoteStatus) Type() protoreflect.EnumType {
	return &file_mult_sign_proto_enumTypes[0]
}

func (x VoteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteStatus.Descriptor instead.
func (VoteStatus) EnumDescriptor() ([]byte, []int) {
	return file_mult_sign_proto_rawDescGZIP(), []int{0}
}

// 多签管理
type MultSignStatus int32

const (
	// 进行中
	MultSignStatus_PROCESSING MultSignStatus = 0
	// 通过
	MultSignStatus_ADOPT MultSignStatus = 1
	// 拒绝
	MultSignStatus_REFUSED MultSignStatus = 2
	// 过期
	MultSignStatus_EXPIRED MultSignStatus = 3
)

// Enum value maps for MultSignStatus.
var (
	MultSignStatus_name = map[int32]string{
		0: "PROCESSING",
		1: "ADOPT",
		2: "REFUSED",
		3: "EXPIRED",
	}
	MultSignStatus_value = map[string]int32{
		"PROCESSING": 0,
		"ADOPT":      1,
		"REFUSED":    2,
		"EXPIRED":    3,
	}
)

func (x MultSignStatus) Enum() *MultSignStatus {
	p := new(MultSignStatus)
	*p = x
	return p
}

func (x MultSignStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MultSignStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mult_sign_proto_enumTypes[1].Descriptor()
}

func (MultSignStatus) Type() protoreflect.EnumType {
	return &file_mult_sign_proto_enumTypes[1]
}

func (x MultSignStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MultSignStatus.Descriptor instead.
func (MultSignStatus) EnumDescriptor() ([]byte, []int) {
	return file_mult_sign_proto_rawDescGZIP(), []int{1}
}

type MultSignInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易ID
	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// 多签时的交易类型
	TxType string `protobuf:"bytes,2,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	// payload的bytes
	PayloadBytes []byte `protobuf:"bytes,3,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	// 截止的区块高度
	DeadlineBlock uint64 `protobuf:"varint,4,opt,name=deadline_block,json=deadlineBlock,proto3" json:"deadline_block,omitempty"`
	// 多签的信息
	VoteInfos []*MultSignVoteInfo `protobuf:"bytes,5,rep,name=voteInfos,proto3" json:"voteInfos,omitempty"`
	// 多签状态
	Status MultSignStatus `protobuf:"varint,6,opt,name=status,proto3,enum=pb.MultSignStatus" json:"status,omitempty"`
}

func (x *MultSignInfo) Reset() {
	*x = MultSignInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mult_sign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultSignInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultSignInfo) ProtoMessage() {}

func (x *MultSignInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mult_sign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultSignInfo.ProtoReflect.Descriptor instead.
func (*MultSignInfo) Descriptor() ([]byte, []int) {
	return file_mult_sign_proto_rawDescGZIP(), []int{0}
}

func (x *MultSignInfo) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *MultSignInfo) GetTxType() string {
	if x != nil {
		return x.TxType
	}
	return ""
}

func (x *MultSignInfo) GetPayloadBytes() []byte {
	if x != nil {
		return x.PayloadBytes
	}
	return nil
}

func (x *MultSignInfo) GetDeadlineBlock() uint64 {
	if x != nil {
		return x.DeadlineBlock
	}
	return 0
}

func (x *MultSignInfo) GetVoteInfos() []*MultSignVoteInfo {
	if x != nil {
		return x.VoteInfos
	}
	return nil
}

func (x *MultSignInfo) GetStatus() MultSignStatus {
	if x != nil {
		return x.Status
	}
	return MultSignStatus_PROCESSING
}

type MultSignVoteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 投票
	Vote VoteStatus `protobuf:"varint,1,opt,name=vote,proto3,enum=pb.VoteStatus" json:"vote,omitempty"`
	// 签名信息
	Endorsement *EndorsementEntry `protobuf:"bytes,2,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
}

func (x *MultSignVoteInfo) Reset() {
	*x = MultSignVoteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mult_sign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultSignVoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultSignVoteInfo) ProtoMessage() {}

func (x *MultSignVoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mult_sign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultSignVoteInfo.ProtoReflect.Descriptor instead.
func (*MultSignVoteInfo) Descriptor() ([]byte, []int) {
	return file_mult_sign_proto_rawDescGZIP(), []int{1}
}

func (x *MultSignVoteInfo) GetVote() VoteStatus {
	if x != nil {
		return x.Vote
	}
	return VoteStatus_DISAGREE
}

func (x *MultSignVoteInfo) GetEndorsement() *EndorsementEntry {
	if x != nil {
		return x.Endorsement
	}
	return nil
}

type MultSignResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易ID
	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// payload_hash
	PayloadHash string `protobuf:"bytes,2,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
}

func (x *MultSignResp) Reset() {
	*x = MultSignResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mult_sign_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultSignResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultSignResp) ProtoMessage() {}

func (x *MultSignResp) ProtoReflect() protoreflect.Message {
	mi := &file_mult_sign_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultSignResp.ProtoReflect.Descriptor instead.
func (*MultSignResp) Descriptor() ([]byte, []int) {
	return file_mult_sign_proto_rawDescGZIP(), []int{2}
}

func (x *MultSignResp) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *MultSignResp) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

var File_mult_sign_proto protoreflect.FileDescriptor

var file_mult_sign_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x01, 0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x53, 0x69, 0x67,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0d, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x32, 0x0a, 0x09, 0x76, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x53, 0x69, 0x67, 0x6e,
	0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x76, 0x6f, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x53, 0x69, 0x67,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x6e, 0x0a, 0x10, 0x4d, 0x75, 0x6c, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x46, 0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x78, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x48, 0x61, 0x73, 0x68, 0x2a, 0x25, 0x0a, 0x0a, 0x56, 0x6f, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x41, 0x47, 0x52, 0x45,
	0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x47, 0x52, 0x45, 0x45, 0x10, 0x01, 0x2a, 0x45,
	0x0a, 0x0e, 0x4d, 0x75, 0x6c, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4f, 0x50, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x45, 0x46, 0x55, 0x53, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49,
	0x52, 0x45, 0x44, 0x10, 0x03, 0x42, 0x3b, 0x0a, 0x18, 0x6f, 0x72, 0x67, 0x2e, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5a, 0x1f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mult_sign_proto_rawDescOnce sync.Once
	file_mult_sign_proto_rawDescData = file_mult_sign_proto_rawDesc
)

func file_mult_sign_proto_rawDescGZIP() []byte {
	file_mult_sign_proto_rawDescOnce.Do(func() {
		file_mult_sign_proto_rawDescData = protoimpl.X.CompressGZIP(file_mult_sign_proto_rawDescData)
	})
	return file_mult_sign_proto_rawDescData
}

var file_mult_sign_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mult_sign_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mult_sign_proto_goTypes = []interface{}{
	(VoteStatus)(0),          // 0: pb.VoteStatus
	(MultSignStatus)(0),      // 1: pb.MultSignStatus
	(*MultSignInfo)(nil),     // 2: pb.MultSignInfo
	(*MultSignVoteInfo)(nil), // 3: pb.MultSignVoteInfo
	(*MultSignResp)(nil),     // 4: pb.MultSignResp
	(*EndorsementEntry)(nil), // 5: pb.EndorsementEntry
}
var file_mult_sign_proto_depIdxs = []int32{
	3, // 0: pb.MultSignInfo.voteInfos:type_name -> pb.MultSignVoteInfo
	1, // 1: pb.MultSignInfo.status:type_name -> pb.MultSignStatus
	0, // 2: pb.MultSignVoteInfo.vote:type_name -> pb.VoteStatus
	5, // 3: pb.MultSignVoteInfo.endorsement:type_name -> pb.EndorsementEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mult_sign_proto_init() }
func file_mult_sign_proto_init() {
	if File_mult_sign_proto != nil {
		return
	}
	file_request_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mult_sign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultSignInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mult_sign_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultSignVoteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mult_sign_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultSignResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mult_sign_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mult_sign_proto_goTypes,
		DependencyIndexes: file_mult_sign_proto_depIdxs,
		EnumInfos:         file_mult_sign_proto_enumTypes,
		MessageInfos:      file_mult_sign_proto_msgTypes,
	}.Build()
	File_mult_sign_proto = out.File
	file_mult_sign_proto_rawDesc = nil
	file_mult_sign_proto_goTypes = nil
	file_mult_sign_proto_depIdxs = nil
}
