// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcNodeClient is the client API for RpcNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcNodeClient interface {
	SendRequest(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*TxResponse, error)
	Subscribe(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (RpcNode_SubscribeClient, error)
	UpdateDebugConfig(ctx context.Context, in *DebugConfigRequest, opts ...grpc.CallOption) (*DebugConfigResponse, error)
	RefreshLogLevelsConfig(ctx context.Context, in *LogLevelsRequest, opts ...grpc.CallOption) (*LogLevelsResponse, error)
	GetChainMakerVersion(ctx context.Context, in *ChainMakerVersionRequest, opts ...grpc.CallOption) (*ChainMakerVersionResponse, error)
	CheckNewBlockChainConfig(ctx context.Context, in *CheckNewBlockChainConfigRequest, opts ...grpc.CallOption) (*CheckNewBlockChainConfigResponse, error)
}

type rpcNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcNodeClient(cc grpc.ClientConnInterface) RpcNodeClient {
	return &rpcNodeClient{cc}
}

func (c *rpcNodeClient) SendRequest(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (*TxResponse, error) {
	out := new(TxResponse)
	err := c.cc.Invoke(ctx, "/pb.RpcNode/SendRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcNodeClient) Subscribe(ctx context.Context, in *TxRequest, opts ...grpc.CallOption) (RpcNode_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &RpcNode_ServiceDesc.Streams[0], "/pb.RpcNode/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &rpcNodeSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RpcNode_SubscribeClient interface {
	Recv() (*SubscribeResult, error)
	grpc.ClientStream
}

type rpcNodeSubscribeClient struct {
	grpc.ClientStream
}

func (x *rpcNodeSubscribeClient) Recv() (*SubscribeResult, error) {
	m := new(SubscribeResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rpcNodeClient) UpdateDebugConfig(ctx context.Context, in *DebugConfigRequest, opts ...grpc.CallOption) (*DebugConfigResponse, error) {
	out := new(DebugConfigResponse)
	err := c.cc.Invoke(ctx, "/pb.RpcNode/UpdateDebugConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcNodeClient) RefreshLogLevelsConfig(ctx context.Context, in *LogLevelsRequest, opts ...grpc.CallOption) (*LogLevelsResponse, error) {
	out := new(LogLevelsResponse)
	err := c.cc.Invoke(ctx, "/pb.RpcNode/RefreshLogLevelsConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcNodeClient) GetChainMakerVersion(ctx context.Context, in *ChainMakerVersionRequest, opts ...grpc.CallOption) (*ChainMakerVersionResponse, error) {
	out := new(ChainMakerVersionResponse)
	err := c.cc.Invoke(ctx, "/pb.RpcNode/GetChainMakerVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcNodeClient) CheckNewBlockChainConfig(ctx context.Context, in *CheckNewBlockChainConfigRequest, opts ...grpc.CallOption) (*CheckNewBlockChainConfigResponse, error) {
	out := new(CheckNewBlockChainConfigResponse)
	err := c.cc.Invoke(ctx, "/pb.RpcNode/CheckNewBlockChainConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcNodeServer is the server API for RpcNode service.
// All implementations must embed UnimplementedRpcNodeServer
// for forward compatibility
type RpcNodeServer interface {
	SendRequest(context.Context, *TxRequest) (*TxResponse, error)
	Subscribe(*TxRequest, RpcNode_SubscribeServer) error
	UpdateDebugConfig(context.Context, *DebugConfigRequest) (*DebugConfigResponse, error)
	RefreshLogLevelsConfig(context.Context, *LogLevelsRequest) (*LogLevelsResponse, error)
	GetChainMakerVersion(context.Context, *ChainMakerVersionRequest) (*ChainMakerVersionResponse, error)
	CheckNewBlockChainConfig(context.Context, *CheckNewBlockChainConfigRequest) (*CheckNewBlockChainConfigResponse, error)
	mustEmbedUnimplementedRpcNodeServer()
}

// UnimplementedRpcNodeServer must be embedded to have forward compatible implementations.
type UnimplementedRpcNodeServer struct {
}

func (UnimplementedRpcNodeServer) SendRequest(context.Context, *TxRequest) (*TxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedRpcNodeServer) Subscribe(*TxRequest, RpcNode_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedRpcNodeServer) UpdateDebugConfig(context.Context, *DebugConfigRequest) (*DebugConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDebugConfig not implemented")
}
func (UnimplementedRpcNodeServer) RefreshLogLevelsConfig(context.Context, *LogLevelsRequest) (*LogLevelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshLogLevelsConfig not implemented")
}
func (UnimplementedRpcNodeServer) GetChainMakerVersion(context.Context, *ChainMakerVersionRequest) (*ChainMakerVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainMakerVersion not implemented")
}
func (UnimplementedRpcNodeServer) CheckNewBlockChainConfig(context.Context, *CheckNewBlockChainConfigRequest) (*CheckNewBlockChainConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNewBlockChainConfig not implemented")
}
func (UnimplementedRpcNodeServer) mustEmbedUnimplementedRpcNodeServer() {}

// UnsafeRpcNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcNodeServer will
// result in compilation errors.
type UnsafeRpcNodeServer interface {
	mustEmbedUnimplementedRpcNodeServer()
}

func RegisterRpcNodeServer(s grpc.ServiceRegistrar, srv RpcNodeServer) {
	s.RegisterService(&RpcNode_ServiceDesc, srv)
}

func _RpcNode_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcNodeServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcNode/SendRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcNodeServer).SendRequest(ctx, req.(*TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcNode_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TxRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RpcNodeServer).Subscribe(m, &rpcNodeSubscribeServer{stream})
}

type RpcNode_SubscribeServer interface {
	Send(*SubscribeResult) error
	grpc.ServerStream
}

type rpcNodeSubscribeServer struct {
	grpc.ServerStream
}

func (x *rpcNodeSubscribeServer) Send(m *SubscribeResult) error {
	return x.ServerStream.SendMsg(m)
}

func _RpcNode_UpdateDebugConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcNodeServer).UpdateDebugConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcNode/UpdateDebugConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcNodeServer).UpdateDebugConfig(ctx, req.(*DebugConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcNode_RefreshLogLevelsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLevelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcNodeServer).RefreshLogLevelsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcNode/RefreshLogLevelsConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcNodeServer).RefreshLogLevelsConfig(ctx, req.(*LogLevelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcNode_GetChainMakerVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainMakerVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcNodeServer).GetChainMakerVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcNode/GetChainMakerVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcNodeServer).GetChainMakerVersion(ctx, req.(*ChainMakerVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcNode_CheckNewBlockChainConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNewBlockChainConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcNodeServer).CheckNewBlockChainConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcNode/CheckNewBlockChainConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcNodeServer).CheckNewBlockChainConfig(ctx, req.(*CheckNewBlockChainConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcNode_ServiceDesc is the grpc.ServiceDesc for RpcNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RpcNode",
	HandlerType: (*RpcNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _RpcNode_SendRequest_Handler,
		},
		{
			MethodName: "UpdateDebugConfig",
			Handler:    _RpcNode_UpdateDebugConfig_Handler,
		},
		{
			MethodName: "RefreshLogLevelsConfig",
			Handler:    _RpcNode_RefreshLogLevelsConfig_Handler,
		},
		{
			MethodName: "GetChainMakerVersion",
			Handler:    _RpcNode_GetChainMakerVersion_Handler,
		},
		{
			MethodName: "CheckNewBlockChainConfig",
			Handler:    _RpcNode_CheckNewBlockChainConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _RpcNode_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc_node.proto",
}
