// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: transaction_pool.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SignalType int32

const (
	SignalType_NO_EVENT           SignalType = 0 // 无交易事件
	SignalType_TRANSACTION_INCOME SignalType = 1 // 新增交易
	SignalType_TRANSACTION_COMMIT SignalType = 2 // 交易提交
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "NO_EVENT",
		1: "TRANSACTION_INCOME",
		2: "TRANSACTION_COMMIT",
	}
	SignalType_value = map[string]int32{
		"NO_EVENT":           0,
		"TRANSACTION_INCOME": 1,
		"TRANSACTION_COMMIT": 2,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_pool_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_transaction_pool_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_transaction_pool_proto_rawDescGZIP(), []int{0}
}

type TxPoolSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxPoolSize int64      `protobuf:"varint,1,opt,name=txPoolSize,proto3" json:"txPoolSize,omitempty"`                    // 交易池当前等待交易大小
	SignalType SignalType `protobuf:"varint,2,opt,name=signalType,proto3,enum=pb.SignalType" json:"signalType,omitempty"` // 事件类型
	ChainId    string     `protobuf:"bytes,3,opt,name=chainId,proto3" json:"chainId,omitempty"`
}

func (x *TxPoolSignal) Reset() {
	*x = TxPoolSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_pool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxPoolSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPoolSignal) ProtoMessage() {}

func (x *TxPoolSignal) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_pool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPoolSignal.ProtoReflect.Descriptor instead.
func (*TxPoolSignal) Descriptor() ([]byte, []int) {
	return file_transaction_pool_proto_rawDescGZIP(), []int{0}
}

func (x *TxPoolSignal) GetTxPoolSize() int64 {
	if x != nil {
		return x.TxPoolSize
	}
	return 0
}

func (x *TxPoolSignal) GetSignalType() SignalType {
	if x != nil {
		return x.SignalType
	}
	return SignalType_NO_EVENT
}

func (x *TxPoolSignal) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

var File_transaction_pool_proto protoreflect.FileDescriptor

var file_transaction_pool_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x78, 0x0a, 0x0c,
	0x54, 0x78, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x78, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x74, 0x78, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2e, 0x0a, 0x0a,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x2a, 0x4a, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x49, 0x4e, 0x43, 0x4f, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x52,
	0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54,
	0x10, 0x02, 0x42, 0x21, 0x5a, 0x1f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72,
	0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2d,
	0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transaction_pool_proto_rawDescOnce sync.Once
	file_transaction_pool_proto_rawDescData = file_transaction_pool_proto_rawDesc
)

func file_transaction_pool_proto_rawDescGZIP() []byte {
	file_transaction_pool_proto_rawDescOnce.Do(func() {
		file_transaction_pool_proto_rawDescData = protoimpl.X.CompressGZIP(file_transaction_pool_proto_rawDescData)
	})
	return file_transaction_pool_proto_rawDescData
}

var file_transaction_pool_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transaction_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transaction_pool_proto_goTypes = []interface{}{
	(SignalType)(0),      // 0: pb.SignalType
	(*TxPoolSignal)(nil), // 1: pb.TxPoolSignal
}
var file_transaction_pool_proto_depIdxs = []int32{
	0, // 0: pb.TxPoolSignal.signalType:type_name -> pb.SignalType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transaction_pool_proto_init() }
func file_transaction_pool_proto_init() {
	if File_transaction_pool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transaction_pool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxPoolSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transaction_pool_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_pool_proto_goTypes,
		DependencyIndexes: file_transaction_pool_proto_depIdxs,
		EnumInfos:         file_transaction_pool_proto_enumTypes,
		MessageInfos:      file_transaction_pool_proto_msgTypes,
	}.Build()
	File_transaction_pool_proto = out.File
	file_transaction_pool_proto_rawDesc = nil
	file_transaction_pool_proto_goTypes = nil
	file_transaction_pool_proto_depIdxs = nil
}
